talent-app/main/default/objects/Comment_Tag__c/Comment_Tag__c.object-meta.xml
<CustomObject>
    <label>Comment Tag</label>
    <nameField>
        <label>Comment Tag Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Comment_Tag__c/fields/Comment_ID__c.field-meta.xml
<CustomField>
    <fullName>Comment_ID__c</fullName>
    <label>Comment ID</label>
    <referenceTo>Skill_Comment__c</referenceTo>
    <relationshipLabel>Comment Tag</relationshipLabel>
    <relationshipName>Skill_Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

talent-app/main/default/objects/Comment_Tag__c/fields/Skill_Comment_ID__c.field-meta.xml
<CustomField>
    <fullName>Skill_Comment_ID__c</fullName>
    <label>Skill Comment ID</label>
    <referenceTo>Skill_Comment__c</referenceTo>
    <relationshipLabel>Comment Tag</relationshipLabel>
    <relationshipName>Skill_Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

talent-app/main/default/objects/Comment_Tag__c/fields/Tag_ID__c.field-meta.xml
<CustomField>
    <fullName>Tag_ID__c</fullName>
    <label>Tag ID</label>
    <referenceTo>Tag__c</referenceTo>
    <relationshipLabel>Comment Tag</relationshipLabel>
    <relationshipName>Tags</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mytalent/main/default/src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Employee_Hiring__c</fullName>
        <label>Employee Hiring</label>
        <referenceTo>Employee_Hiring__c</referenceTo>
        <relationshipLabel>Employee</relationshipLabel>
        <relationshipName>Employee</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Display Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mytalent/main/default/src/objects/Employee_Hiring__c.object
<CustomObject>
    <label>Employee Hiring</label>
    <nameField>
        <displayFormat>PVT-{0000}</displayFormat>
        <label>Employee Code</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Personality_Comment__c/Personality_Comment__c.object-meta.xml
<CustomObject>
    <label>Personality Comment</label>
    <nameField>
        <label>Content</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Personality_Comment__c/fields/Create_By__c.field-meta.xml
<CustomField>
    <fullName>Create_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Create By</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Personality Comment (Create By)</relationshipLabel>
    <relationshipName>Personality_Comment1</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Personality_Comment__c/fields/Create_When__c.field-meta.xml
<CustomField>
    <fullName>Create_When__c</fullName>
    <label>Create When</label>
    <type>DateTime</type>
</CustomField>

talent-app/main/default/objects/Personality_Comment__c/fields/Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>Employee_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee ID</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Personality Comment</relationshipLabel>
    <relationshipName>Personality_Comment</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Personality_Comment__c/fields/Personality_Method_ID__c.field-meta.xml
<CustomField>
    <fullName>Personality_Method_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Personality Method ID</label>
    <referenceTo>Personality_Method__c</referenceTo>
    <relationshipLabel>Personality Comment</relationshipLabel>
    <relationshipName>Personality_Comment</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Personality_Comment__c/fields/Personality_Type_ID__c.field-meta.xml
<CustomField>
    <fullName>Personality_Type_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Personality Type ID</label>
    <referenceTo>Personality_Type__c</referenceTo>
    <relationshipLabel>Personality Comment</relationshipLabel>
    <relationshipName>Personality_Comment</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Personality_Comment_Tag__c/Personality_Comment_Tag__c.object-meta.xml
<CustomObject>
    <label>Personality Comment Tag</label>
    <nameField>
        <label>Comment Tag Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

talent-app/main/default/objects/Personality_Comment_Tag__c/fields/Comment_ID__c.field-meta.xml
<CustomField>
    <fullName>Comment_ID__c</fullName>
    <label>Comment ID</label>
    <referenceTo>Personality_Comment__c</referenceTo>
    <relationshipLabel>Personality Comment Tag</relationshipLabel>
    <relationshipName>Personality_Comments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

talent-app/main/default/objects/Personality_Comment_Tag__c/fields/Tag_ID__c.field-meta.xml
<CustomField>
    <fullName>Tag_ID__c</fullName>
    <label>Tag ID</label>
    <referenceTo>Tag__c</referenceTo>
    <relationshipLabel>Personality Comment Tag</relationshipLabel>
    <relationshipName>Personality_Comment_Tag</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

talent-app/main/default/objects/Personality_Method__c/Personality_Method__c.object-meta.xml
<CustomObject>
    <label>Personality Method</label>
    <nameField>
        <label>Personality Method</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Personality_Type__c/Personality_Type__c.object-meta.xml
<CustomObject>
    <label>Personality Type</label>
    <nameField>
        <label>Personality Type Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Skill_Comment__c/Skill_Comment__c.object-meta.xml
<CustomObject>
    <label>Skill Comment</label>
    <nameField>
        <label>Content</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Skill_Comment__c/fields/Create_By__c.field-meta.xml
<CustomField>
    <fullName>Create_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Create By</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Skill Comment (Create By)</relationshipLabel>
    <relationshipName>Skill_Comment1</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Skill_Comment__c/fields/Create_When_Disp__c.field-meta.xml
<CustomField>
    <fullName>Create_When_Disp__c</fullName>
    <formula>IF(
ISBLANK(Create_When__c),
"",
TEXT(YEAR(DATEVALUE(Create_When__c))) + "/" + TEXT(MONTH(DATEVALUE(Create_When__c))) + "/" +TEXT(DAY(DATEVALUE(Create_When__c)))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FML Create When</label>
    <type>Text</type>
</CustomField>

talent-app/main/default/objects/Skill_Comment__c/fields/Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>Employee_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee ID</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Skill Comment</relationshipLabel>
    <relationshipName>Skill_Comment</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Skill_Comment__c/fields/Skill_ID__c.field-meta.xml
<CustomField>
    <fullName>Skill_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Skill ID</label>
    <referenceTo>Skill_Type__c</referenceTo>
    <relationshipLabel>Skill Comment</relationshipLabel>
    <relationshipName>Skill_Comment</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Skill_Comment__c/fields/Skill_Level_ID__c.field-meta.xml
<CustomField>
    <fullName>Skill_Level_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Skill Level ID</label>
    <referenceTo>Skill_Level__c</referenceTo>
    <relationshipLabel>Skill Comment</relationshipLabel>
    <relationshipName>Skill_Comment</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Skill_Level__c/Skill_Level__c.object-meta.xml
<CustomObject>
    <label>Skill Level</label>
    <nameField>
        <label>Skill Level Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Skill_Type__c/Skill_Type__c.object-meta.xml
<CustomObject>
    <label>Skill Type</label>
    <nameField>
        <label>Type Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Tag__c/Tag__c.object-meta.xml
<CustomObject>
    <label>Tag</label>
    <nameField>
        <label>Comment Tag Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/classes/TMSaveComment.cls
public class TMSaveComment {
    @AuraEnabled
	public static List<Tag__c> getTags () {
    	return [SELECT ID, Name FROM Tag__c];
    }
    
    @AuraEnabled
	public static List<Object> addSkillComment (String createById, String employeeId, String typeId, String modeId, String selectedTagsId, String comment) {
        List<Object> result = new List<Object>();
        Map<String, List<Skill_Comment__c>> mapComment = new Map<String, List<Skill_Comment__c>>();
        Savepoint savePoint = Database.setSavepoint();
        TMResponseMessage message = new TMResponseMessage();
        
        if (!TMHome.isManager()) {
            message.status = 'error';
            message.message = '権限がない。';
            result.Add(message);
            return result;
        }
        
        try
        {
            DateTime current = system.now();
            Skill_Comment__c item = new Skill_Comment__c();
            item.Create_By__c = createById;
            item.Create_When__c = current;
            item.Employee_ID__c = employeeId;
            item.Last_Modified_When__c = current;
            item.Name = comment;
            item.Skill_ID__c = typeId;
            item.Skill_Level_ID__c  = modeId;
            insert item;
            
            List<Comment_Tag__c> lstCommentTag = new List<Comment_Tag__c>();
            for (Id tagId : selectedTagsId.split(';')) {
                lstCommentTag.Add(new Comment_Tag__c(
                    Name = Id.valueOf(item.Id) + '-' + Id.valueOf(tagId),
                    Comment_ID__c = item.Id,
                    Tag_ID__c = tagId
                ));
            }
            insert lstCommentTag;
            
            message.status = 'OK';
            result.Add(message);
            mapComment.put(String.valueOf(item.Create_When__c.year()), getSkillComment(item.Id));
            result.Add(mapComment);
        }
        catch(Exception e)
        {
        	Database.rollback(savePoint);
            message.status = 'error';
            message.message = e.getMessage();
            result.Add(message);
        }
        
        return result;
    }
    
    @AuraEnabled
	public static List<Object> addPersonalityComment (String createById, String employeeId, String typeId, String modeId, String selectedTagsId, String comment) {
        List<Object> result = new List<Object>();
        Map<String, List<Personality_Comment__c>> mapComment = new Map<String, List<Personality_Comment__c>>();
        Savepoint savePoint = Database.setSavepoint();
        TMResponseMessage message = new TMResponseMessage();
        
        if (!TMHome.isManager()) {
            message.status = 'error';
            message.message = '権限がない。';
            result.Add(message);
            return result;
        }
        
        try
        {
            DateTime current = system.now();
            Personality_Comment__c  item = new Personality_Comment__c();
            item.Create_By__c = createById;
            item.Create_When__c = current;
            item.Employee_ID__c = employeeId;
            item.Last_Modified_When__c = current;
            item.Name = comment;
            item.Personality_Type_ID__c = typeId;
            item.Personality_Method_ID__c  = modeId;
            insert item;
            
            List<Personality_Comment_Tag__c> lstCommentTag = new List<Personality_Comment_Tag__c>();
            for (Id tagId : selectedTagsId.split(';')) {
                lstCommentTag.Add(new Personality_Comment_Tag__c(
                    Name = Id.valueOf(item.Id) + '-' + Id.valueOf(tagId),
                    Comment_ID__c = item.Id,
                    Tag_ID__c = tagId
                ));
            }
            insert lstCommentTag;
            
            message.status = 'OK';
            result.Add(message);
            mapComment.put(String.valueOf(item.Create_When__c.year()), getPersonalityComment(item.Id));
            result.Add(mapComment);
        }
        catch(Exception e)
        {
        	Database.rollback(savePoint);
            message.status = 'error';
            message.message = e.getMessage();
            result.Add(message);
        }
        
        return result;
    }
    
    @AuraEnabled
	public static List<Object> editSkillComment (Id itemId, String selectedTagsId, String comment) {
        List<Object> result = new List<Object>();
        Map<String, List<Skill_Comment__c>> mapComment = new Map<String, List<Skill_Comment__c>>();
        Savepoint savePoint = Database.setSavepoint();
        TMResponseMessage message = new TMResponseMessage();
        
        if (!TMHome.isManager()) {
            message.status = 'error';
            message.message = '権限がない。';
            result.Add(message);
            return result;
        }
        
        List<Skill_Comment__c> item = getSkillComment(itemId);
        if (item.isEmpty()) {
            message.status = 'error';
            message.message = 'データが存在していません。';
            result.Add(message);
            return result;
        }
        if(TMHome.getCurrentUser().Id != item[0].Create_By__c) {
            message.status = 'error';
            message.message = 'このデータに権限がない。';
            result.Add(message);
            return result;
        }
        
        String[] arrSelectedTagsId = selectedTagsId.split(';');
        try
        {
            DateTime current = system.now();
            item[0].Name = comment;
            item[0].Last_Modified_When__c = current;
            update item;
            
            List<Comment_Tag__c> lstInsertCommentTag = new List<Comment_Tag__c>();
            for (Id tagId : arrSelectedTagsId) {
                if ([SELECT Id 
                     FROM Comment_Tag__c 
                     WHERE Comment_ID__c = :item[0].Id 
                     	AND Tag_ID__c = :tagId
       			].isEmpty()) {
                    lstInsertCommentTag.Add(new Comment_Tag__c(
                        Name = Id.valueOf(item[0].Id) + '-' + Id.valueOf(tagId),
                        Comment_ID__c = item[0].Id,
                        Tag_ID__c = tagId
                    ));
                }
            }
            insert lstInsertCommentTag;
            
            List<Comment_Tag__c> lstDeleteCommentTag = [
                SELECT ID 
                FROM Comment_Tag__c 
                WHERE Comment_ID__c = :item[0].Id 
                	AND Tag_ID__c NOT IN: arrSelectedTagsId
            ];
            delete lstDeleteCommentTag;
            
            message.status = 'OK';
            result.Add(message);
            mapComment.put(String.valueOf(item[0].Create_When__c.year()), getSkillComment(item[0].Id));
            result.Add(mapComment);
        }
        catch(Exception e)
        {
        	Database.rollback(savePoint);
            message.status = 'error';
            message.message = e.getMessage();
            result.Add(message);
        }
        
        return result;
    }
    
    @AuraEnabled
	public static List<Object> editPersonalityComment (Id itemId, String selectedTagsId, String comment) {
        List<Object> result = new List<Object>();
        Map<String, List<Personality_Comment__c>> mapComment = new Map<String, List<Personality_Comment__c>>();
        Savepoint savePoint = Database.setSavepoint();
        TMResponseMessage message = new TMResponseMessage();
        
        if (!TMHome.isManager()) {
            message.status = 'error';
            message.message = '権限がない。';
            result.Add(message);
            return result;
        }
        
        List<Personality_Comment__c> item = getPersonalityComment(itemId);
        if (item.isEmpty()) {
            message.status = 'error';
            message.message = 'データが存在していません。';
            result.Add(message);
            return result;
        }
        if(TMHome.getCurrentUser().Id != item[0].Create_By__c) {
            message.status = 'error';
            message.message = 'このデータに権限がない。';
            result.Add(message);
            return result;
        }
        
        String[] arrSelectedTagsId = selectedTagsId.split(';');
        try
        {
            DateTime current = system.now();
            item[0].Name = comment;
            item[0].Last_Modified_When__c = current;
            update item;
            
            List<Personality_Comment_Tag__c> lstInsertCommentTag = new List<Personality_Comment_Tag__c>();
            for (Id tagId : arrSelectedTagsId) {
                if ([SELECT Id 
                     FROM Personality_Comment_Tag__c 
                     WHERE Comment_ID__c = :item[0].Id 
                     	AND Tag_ID__c = :tagId
       			].isEmpty()) {
                    lstInsertCommentTag.Add(new Personality_Comment_Tag__c(
                        Name = Id.valueOf(item[0].Id) + '-' + Id.valueOf(tagId),
                        Comment_ID__c = item[0].Id,
                        Tag_ID__c = tagId
                    ));
                }
            }
            insert lstInsertCommentTag;
            
            List<Personality_Comment_Tag__c> lstDeleteCommentTag = [
                SELECT ID 
                FROM Personality_Comment_Tag__c 
                WHERE Comment_ID__c = :item[0].Id 
                	AND Tag_ID__c NOT IN: arrSelectedTagsId
            ];
            delete lstDeleteCommentTag;
            
            message.status = 'OK';
            result.Add(message);
            mapComment.put(String.valueOf(item[0].Create_When__c.year()), getPersonalityComment(item[0].Id));
            result.Add(mapComment);
        }
        catch(Exception e)
        {
        	Database.rollback(savePoint);
            message.status = 'error';
            message.message = e.getMessage();
            result.Add(message);
        }
        
        return result;
    }
    
    @AuraEnabled
    public static List<Object> deleteSkillComment(Id itemId) {
        List<Object> result = new List<Object>();
        Savepoint savePoint = Database.setSavepoint();
        TMResponseMessage message = new TMResponseMessage();
        
        if (!TMHome.isManager()) {
            message.status = 'error';
            message.message = '権限がない。';
            result.Add(message);
            return result;
        }
        
        List<Skill_Comment__c> item = getSkillComment(itemId);
        if (item.isEmpty()) {
            message.status = 'error';
            message.message = 'データが存在していません。';
            result.Add(message);
            return result;
        }
        if(TMHome.getCurrentUser().Id != item[0].Create_By__c) {
            message.status = 'error';
            message.message = 'このデータに権限がない。';
            result.Add(message);
            return result;
        }
        
        try
        {
            delete item;
            delete [SELECT ID from Comment_Tag__c WHERE Comment_ID__c = :item[0].Id];
            
            message.status = 'OK';
            result.Add(message);
        }
        catch(Exception e)
        {
        	Database.rollback(savePoint);
            message.status = 'error';
            message.message = e.getMessage();
            result.Add(message);
        }
        
        return result;
	}
    
    @AuraEnabled
    public static List<Object> deletePersonalityComment(Id itemId) {
        List<Object> result = new List<Object>();
        Savepoint savePoint = Database.setSavepoint();
        TMResponseMessage message = new TMResponseMessage();
        
        if (!TMHome.isManager()) {
            message.status = 'error';
            message.message = '権限がない。';
            result.Add(message);
            return result;
        }
        
       	List<Personality_Comment__c> item = getPersonalityComment(itemId);
        if (item.isEmpty()) {
            message.status = 'error';
            message.message = 'データが存在していません。';
            result.Add(message);
            return result;
        }
        if(TMHome.getCurrentUser().Id != item[0].Create_By__c) {
            message.status = 'error';
            message.message = 'このデータに権限がない。';
            result.Add(message);
            return result;
        }
        
        try
        {
            delete item;
            delete [SELECT ID from Personality_Comment_Tag__c WHERE Comment_ID__c = :item[0].Id];
            
            message.status = 'OK';
            result.Add(message);
        }
        catch(Exception e)
        {
        	Database.rollback(savePoint);
            message.status = 'error';
            message.message = e.getMessage();
            result.Add(message);
        }
        
        return result;
	}
    
    @AuraEnabled
    public static List<Skill_Comment__c> getSkillComment(Id itemId) {
        return [SELECT 
                Skill_Comment__c.ID,
                Create_When__c,
            	Create_When_Disp__c,
                Create_By__r.Name,
                Create_By__r.Employee_Hiring__r.Team__c,
                LastModifiedById,
                Last_Modified_When__c,
                Name,
                Skill_ID__c,
                Skill_ID__r.Name,
                Skill_Level_ID__c,
                Skill_Level_ID__r.Name,
                ( SELECT Tag_ID__r.Name FROM Skill_Comments__r )
            FROM Skill_Comment__c
            WHERE Id = :itemId
 		];
	}
    
    @AuraEnabled
    public static List<Personality_Comment__c> getPersonalityComment(Id itemId) {
        return [SELECT 
                Personality_Comment__c.ID,
                Create_When__c,
            	Create_When_Disp__c,
                Create_By__r.Name,
                Create_By__r.Employee_Hiring__r.Team__c,
                LastModifiedById,
                Last_Modified_When__c,
                Name,
                Personality_Type_ID__c,
                Personality_Type_ID__r.Name,
            	Personality_Method_ID__c,
                Personality_Method_ID__r.Name,
                ( SELECT Tag_ID__r.Name FROM Personality_Comments__r )
            FROM Personality_Comment__c
            WHERE Id = :itemId
 		];
	}
}