talent-app/main/default/objects/Comment_Tag__c/Comment_Tag__c.object-meta.xml
<CustomObject>
    <label>Comment Tag</label>
    <nameField>
        <label>Comment Tag Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Comment_Tag__c/fields/Comment_ID__c.field-meta.xml
<CustomField>
    <fullName>Comment_ID__c</fullName>
    <label>Comment ID</label>
    <referenceTo>Skill_Comment__c</referenceTo>
    <relationshipLabel>Comment Tag</relationshipLabel>
    <relationshipName>Skill_Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

talent-app/main/default/objects/Comment_Tag__c/fields/Skill_Comment_ID__c.field-meta.xml
<CustomField>
    <fullName>Skill_Comment_ID__c</fullName>
    <label>Skill Comment ID</label>
    <referenceTo>Skill_Comment__c</referenceTo>
    <relationshipLabel>Comment Tag</relationshipLabel>
    <relationshipName>Skill_Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

talent-app/main/default/objects/Comment_Tag__c/fields/Tag_ID__c.field-meta.xml
<CustomField>
    <fullName>Tag_ID__c</fullName>
    <label>Tag ID</label>
    <referenceTo>Tag__c</referenceTo>
    <relationshipLabel>Comment Tag</relationshipLabel>
    <relationshipName>Tags</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

mytalent/main/default/src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Employee_Hiring__c</fullName>
        <label>Employee Hiring</label>
        <referenceTo>Employee_Hiring__c</referenceTo>
        <relationshipLabel>Employee</relationshipLabel>
        <relationshipName>Employee</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Display Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mytalent/main/default/src/objects/Employee_Hiring__c.object
<CustomObject>
    <label>Employee Hiring</label>
    <nameField>
        <displayFormat>PVT-{0000}</displayFormat>
        <label>Employee Code</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Skill_Comment__c/Skill_Comment__c.object-meta.xml
<CustomObject>
    <label>Skill Comment</label>
    <nameField>
        <label>Content</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Skill_Comment__c/fields/Create_By__c.field-meta.xml
<CustomField>
    <fullName>Create_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Create By</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Skill Comment (Create By)</relationshipLabel>
    <relationshipName>Skill_Comment1</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Skill_Comment__c/fields/Create_When_Disp__c.field-meta.xml
<CustomField>
    <fullName>Create_When_Disp__c</fullName>
    <formula>IF(
ISBLANK(Create_When__c),
"",
TEXT(YEAR(DATEVALUE(Create_When__c))) + "/" + TEXT(MONTH(DATEVALUE(Create_When__c))) + "/" +TEXT(DAY(DATEVALUE(Create_When__c)))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FML Create When</label>
    <type>Text</type>
</CustomField>

talent-app/main/default/objects/Skill_Comment__c/fields/Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>Employee_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee ID</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Skill Comment</relationshipLabel>
    <relationshipName>Skill_Comment</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Skill_Comment__c/fields/Skill_ID__c.field-meta.xml
<CustomField>
    <fullName>Skill_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Skill ID</label>
    <referenceTo>Skill_Type__c</referenceTo>
    <relationshipLabel>Skill Comment</relationshipLabel>
    <relationshipName>Skill_Comment</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Skill_Comment__c/fields/Skill_Level_ID__c.field-meta.xml
<CustomField>
    <fullName>Skill_Level_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Skill Level ID</label>
    <referenceTo>Skill_Level__c</referenceTo>
    <relationshipLabel>Skill Comment</relationshipLabel>
    <relationshipName>Skill_Comment</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Skill_Level__c/Skill_Level__c.object-meta.xml
<CustomObject>
    <label>Skill Level</label>
    <nameField>
        <label>Skill Level Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Skill_Type__c/Skill_Type__c.object-meta.xml
<CustomObject>
    <label>Skill Type</label>
    <nameField>
        <label>Type Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Tag__c/Tag__c.object-meta.xml
<CustomObject>
    <label>Tag</label>
    <nameField>
        <label>Comment Tag Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/classes/TMSkillComment.cls
public class TMSkillComment {
	@AuraEnabled
   	public static List<Object> fetchSkillComment(Id employeeId, Id skillId, Id skillLevelId, String top, String skip) {
        Integer iTop = Integer.valueOf(top);
       	Integer iSkip = Integer.valueOf(skip);
        String query = '';
        
        query += 'SELECT Skill_Comment__c.ID, ' +
            			'Create_When_Disp__c, ' +
                        'Create_By__r.Name, ' +
            			'Create_By__r.Employee_Hiring__r.Team__c, ' +
                        'LastModifiedById, ' +
                        'Last_Modified_When__c, ' +
                        'Name, ' +
            			'Skill_ID__c, ' +
                        'Skill_ID__r.Name, ' +
            			'Skill_Level_ID__c, ' +
                        'Skill_Level_ID__r.Name, ' +
            			'( SELECT Tag_ID__r.Name FROM Skill_Comments__r ) ' +
            'FROM Skill_Comment__c ' +
            'WHERE Employee_ID__c = :employeeID ' +
            'AND Skill_ID__c = :skillId ' +
            'AND Skill_Level_ID__c = :skillLevelId ' +
            'ORDER BY Create_When__c DESC ' ;
        
        List<Object> result = new List<Object>();
        result.Add(Database.query(query).Size());
        query += 'LIMIT :iTop ' +
            'OFFSET :iSkip';
        result.Add(Database.query(query));
        
        return result;
	}
}