mytalent/main/default/src/objects/Employee__c.object
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Display Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

talent-app/main/default/objects/Employee_Project__c/Employee_Project__c.object-meta.xml
<CustomObject>
    <label>Employee Project</label>
    <nameField>
        <label>Code Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Employee_Project__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Project</relationshipLabel>
    <relationshipName>Employee_Project</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Employee_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Employee Project</relationshipLabel>
    <relationshipName>Employee_Project</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Employee_Skill__c/Employee_Skill__c.object-meta.xml
<CustomObject>
    <label>Employee Skill</label>
    <nameField>
        <label>Code Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Employee_Skill__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Skill</relationshipLabel>
    <relationshipName>Employee_Skill</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Employee_Skill__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Employee Skill</relationshipLabel>
    <relationshipName>Employee_Skill</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Employee_Skill__c/fields/Skill_Label_Ref__c.field-meta.xml
<CustomField>
    <fullName>Skill_Label_Ref__c</fullName>
    <formula>Skill__r.Name + "    " + TEXT(Skill_Level__r.Skill_Num__c)</formula>
    <label>FML Skill Label</label>
    <type>Text</type>
</CustomField>

talent-app/main/default/objects/Employee_Skill__c/fields/Skill_Level__c.field-meta.xml
<CustomField>
    <fullName>Skill_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill Level</label>
    <referenceTo>Skill_Level__c</referenceTo>
    <relationshipLabel>Employee Skill</relationshipLabel>
    <relationshipName>Employee_Skill</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Employee_Skill__c/fields/Skill_Name_Disp__c.field-meta.xml
<CustomField>
    <fullName>Skill_Name_Disp__c</fullName>
    <formula>Skill__r.Name</formula>
    <label>FML Skill Name</label>
    <type>Text</type>
</CustomField>

talent-app/main/default/objects/Employee_Skill__c/fields/Skill_Value_Ref__c.field-meta.xml
<CustomField>
    <fullName>Skill_Value_Ref__c</fullName>
    <formula>Skill__c + ";" + Skill__r.Name + ";" + Skill_Level__c + ";" + TEXT(Skill_Level__r.Skill_Num__c)</formula>
    <label>FML Skill Value</label>
    <type>Text</type>
</CustomField>

talent-app/main/default/objects/Employee_Skill__c/fields/Type_Name_Disp__c.field-meta.xml
<CustomField>
    <fullName>Type_Name_Disp__c</fullName>
    <formula>Skill__r.Skill_Type__r.Name</formula>
    <label>FML Type Name</label>
    <type>Text</type>
</CustomField>

talent-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Project_Skill__c/Project_Skill__c.object-meta.xml
<CustomObject>
    <label>Project Skill</label>
    <nameField>
        <label>Code Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

talent-app/main/default/objects/Project_Skill__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Project Skill</relationshipLabel>
    <relationshipName>Project_Skill</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Project_Skill__c/fields/Employee_Project__c.field-meta.xml
<CustomField>
    <fullName>Employee_Project__c</fullName>
    <label>Employee Project</label>
    <referenceTo>Employee_Project__c</referenceTo>
    <relationshipLabel>Project Skill</relationshipLabel>
    <relationshipName>Project_Skill</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

talent-app/main/default/objects/Project_Skill__c/fields/Employee_Skill__c.field-meta.xml
<CustomField>
    <fullName>Employee_Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Skill</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Employee_Skill__c.Employee__c</field>
            <operation>equals</operation>
            <valueField>$Source.Employee__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Employee_Skill__c</referenceTo>
    <relationshipLabel>Project Skill</relationshipLabel>
    <relationshipName>Project_Skill</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Project_Skill__c/fields/Skill_Label_Ref__c.field-meta.xml
<CustomField>
    <fullName>Skill_Label_Ref__c</fullName>
    <formula>Employee_Skill__r.Skill__r.Name + "    " + TEXT(Skill_Level__r.Skill_Num__c)</formula>
    <label>FML Skill Label</label>
    <type>Text</type>
</CustomField>

talent-app/main/default/objects/Project_Skill__c/fields/Skill_Level__c.field-meta.xml
<CustomField>
    <fullName>Skill_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill Level</label>
    <referenceTo>Skill_Level__c</referenceTo>
    <relationshipLabel>Project Skill</relationshipLabel>
    <relationshipName>Project_Skill</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Project_Skill__c/fields/Skill_Name_Disp__c.field-meta.xml
<CustomField>
    <fullName>Skill_Name_Disp__c</fullName>
    <formula>Employee_Skill__r.Skill__r.Name</formula>
    <label>FML Skill Name</label>
    <type>Text</type>
</CustomField>

talent-app/main/default/objects/Project_Skill__c/fields/Skill_Value_Ref__c.field-meta.xml
<CustomField>
    <fullName>Skill_Value_Ref__c</fullName>
    <formula>Employee_Skill__r.Skill__c + ";" + Employee_Skill__r.Skill__r.Name + ";" + Skill_Level__c + ";" + TEXT(Skill_Level__r.Skill_Num__c)</formula>
    <label>FML Skill Value</label>
    <type>Text</type>
</CustomField>

talent-app/main/default/objects/Project_Skill__c/fields/Type_Name_Disp__c.field-meta.xml
<CustomField>
    <fullName>Type_Name_Disp__c</fullName>
    <formula>Employee_Skill__r.Skill__r.Skill_Type__r.Name</formula>
    <label>FML Type Name</label>
    <type>Text</type>
</CustomField>

talent-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Skill__c/fields/Skill_Type__c.field-meta.xml
<CustomField>
    <fullName>Skill_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill Type</label>
    <referenceTo>Skill_Type__c</referenceTo>
    <relationshipLabel>Skill</relationshipLabel>
    <relationshipName>Skill</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Skill_Level__c/Skill_Level__c.object-meta.xml
<CustomObject>
    <label>Skill Level</label>
    <nameField>
        <label>Skill Level Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Skill_Level__c/fields/Skill_Num__c.field-meta.xml
<CustomField>
    <fullName>Skill_Num__c</fullName>
    <label>Skill Num</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

talent-app/main/default/objects/Skill_Type__c/Skill_Type__c.object-meta.xml
<CustomObject>
    <label>Skill Type</label>
    <nameField>
        <label>Type Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Skill_Type__c/fields/Expanded__c.field-meta.xml
<CustomField>
    <fullName>Expanded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Expanded</label>
    <type>Checkbox</type>
</CustomField>

talent-app/main/default/objects/Skill_Type__c/fields/Icon_Disp__c.field-meta.xml
<CustomField>
    <fullName>Icon_Disp__c</fullName>
    <formula>CASE(Order__c, 
1, "standard:goals", 
2, "standard:lead", 
3, "standard:solution", 
"" 
)</formula>
    <label>FML Icon</label>
    <type>Text</type>
</CustomField>

talent-app/main/default/classes/TMSkillCRUD.cls
public class TMSkillCRUD {
    /***********************************/
    /******              SELECT               ******/
    /***********************************/
    /* Count number of indivisual Skills */
    public integer toCountSkill(Id employeeId) {
        String query = 'SELECT COUNT() ' +
            'FROM Employee_Skill__c ' +
            'WHERE Employee__c = :employeeId';
        integer count= Database.countQuery(query);
        return count;
    }
    
    /* Get list all Employee Skills group by Skill types */
    public List<Object> toGetListSkills(Id employeeId) {
        return toGetListSkills(employeeId, null);
    }
    
    /* Get list all Project Skills group by Skill types */
    public List<Object> toGetListSkills(Id employeeId, Id projectId) {
        List<Object> resultObj = new List<Object>();
        List<Skill_Type__c> typeList = toFetchSkillType();
        
        for (Skill_Type__c typeItem : typeList) {
            List<Object> result = new List<Object>();
            Map<String, Object> mapObj = new Map<String, Object>();
            // Get info by Skill type
            result = projectId == null ? fetchSkill(employeeId, typeItem.Id) : fetchPJSkill(employeeId, projectId, typeItem.Id);
            // Put data to map
            mapObj.put('key', typeItem);
            mapObj.put('value', result);
            // Assign to list
            resultObj.add(mapObj);
        }
        
        return resultObj;
    }
    
    /* Get list all Employee Skills of each Projects  */
    public List<Object> toGetListPJSkills(Id employeeId) {
        List<Object> resultPJObj = new List<Object>();
        List<Employee_Project__c> pjList = toFetchProject(employeeId);
        
        for (Employee_Project__c pjItem : pjList) {
            Map<String, Object> mapObj = new Map<String, Object>();
            // Get info
        	List<Object> resultObj = toGetListSkills(employeeId, pjItem.Id);
            // Put data to map
            mapObj.put('key', pjItem);
            mapObj.put('value', resultObj);
            // Assign to list
            resultPJObj.add(mapObj);
        }
        
        return resultPJObj;
    }
	
    /* Get list all Skill types  */
    public List<Skill_Type__c> toFetchSkillType() {
        return [SELECT Id, Name, Order__c, Expanded__c, Icon_Disp__c  FROM Skill_Type__c ORDER BY Order__c];
    }
    
    /* Get list all Skill levels  */
    public List<Skill_Level__c> toFetchSkillLevel() {
        return [SELECT Id, Name, Skill_Num__c, Icon__c FROM Skill_Level__c ORDER BY Order__c];
	}
    
    /* Get list all Projects by EmpId  */
    public List<Employee_Project__c> toFetchProject(Id employeeId) {
        return [
            SELECT Employee__r.Name, Id, Name, Project__r.Name
            FROM Employee_Project__c
            WHERE Employee__c = :employeeId
        ];
    }
	
    /* Get list by Skill types */
    public List<Object> fetchSkill(Id employeeId, Id typeId) {
        String query = cmmFetchSkill();
        if (employeeId != null) {
            query += 'WHERE Employee__c = :employeeId ';
        }
        if (typeId != null) {
            query += 'AND Skill__r.Skill_Type__c = :typeId';
        }
        
        return Database.query(query);
    }
	
    /* Get list by Skill types */
    public List<Object> fetchPJSkill(Id employeeId, Id projectId, Id typeId) {
        String query = cmmFetchPJSkill();
        if (projectId != null) {
            query += 'WHERE Employee_Project__c = :projectId ';
        }
        if (typeId != null) {
            query += 'AND Employee_Skill__r.Skill__r.Skill_Type__c = :typeId';
        }
        
        return Database.query(query);
    }
 	
    /* Get Employee Skill info */
    public Employee_Skill__c getEmpSkill(String currId) {
        try {
            String query = cmmFetchSkill();
            query += 'WHERE Id = :currId ';
            return Database.query(query);
        } catch(Exception e) {
            throw new MyException(TMErrorMessage.ERR_EMPTY);
        }
    }
    
    /* Get Project Skill info */
    public Project_Skill__c getProjectSkill(String currId) {
        try {
            String query = cmmFetchPJSkill();
            query += 'WHERE Id = :currId ';
            return Database.query(query);
        } catch(Exception e) {
            throw new MyException(TMErrorMessage.ERR_EMPTY);
        }
    }
	
    
    /***********************************/
    /******       COMMON QUERY       ******/
    /***********************************/
    /* Common query for get Employee Skill info */
    private String cmmFetchSkill() {
        String query = '';
        query += 'SELECT Employee__r.Name, Id, Name, Skill__c, Skill_Level__c, ' +
            	'Skill__r.Name, Skill__r.Skill_Type__r.Name, ' +
            	'Skill__r.Skill_Type__r.Order__c, ' +
            	'Skill_Level__r.Name, Skill_Level__r.Skill_Num__c, ' +
            	'Type_Name_Disp__c, Skill_Name_Disp__c, Skill_Label_Ref__c, Skill_Value_Ref__c ' +
            'FROM Employee_Skill__c ';
        return query;
    }
    
    /* Common query for get Project Skill info */
    private String cmmFetchPJSkill() {
        String query = '';
        query += 'SELECT Employee__r.Name, Id, ' +
            	'Employee_Project__c, Employee_Project__r.Project__c, ' +
            	'Employee_Skill__r.Skill__c, Skill_Level__c, ' +
            	'Skill_Level__r.Skill_Num__c, ' +
            	'Employee_Project__r.Project__r.Name, ' +
            	'Employee_Skill__r.Skill__r.Name, ' +
            	'Employee_Skill__r.Skill__r.Skill_Type__r.Name, ' +
            	'Employee_Skill__r.Skill__r.Skill_Type__r.Order__c, ' +           
            	'Employee_Skill__r.Skill_Level__r.Name, ' +
            	'Employee_Skill__r.Skill_Level__r.Skill_Num__c, ' +
            	'Type_Name_Disp__c, Skill_Name_Disp__c, Skill_Label_Ref__c, Skill_Value_Ref__c ' +
            'FROM Project_Skill__c ';
        return query;
    }
}