mytalent/main/default/src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Birthday_Disp__c</fullName>
        <formula>IF( 
ISBLANK(Brithday__c), 
&quot;&quot;, 
TEXT(YEAR(Brithday__c))+ &quot;/&quot; +TEXT(MONTH(Brithday__c))+ &quot;/&quot; +TEXT(DAY(Brithday__c)) 
+ &quot;（&quot; + TEXT(FLOOR((TODAY() - Brithday__c)/365.2425)) + &quot;歳）&quot; 
)</formula>
        <label>FML Birthday</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brithday__c</fullName>
        <label>Brithday</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Employee_Hiring__c</fullName>
        <label>Employee Hiring</label>
        <referenceTo>Employee_Hiring__c</referenceTo>
        <relationshipLabel>Employee</relationshipLabel>
        <relationshipName>Employee</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>First_Name_Kana__c</fullName>
        <label>First Name Kana</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender_Disp__c</fullName>
        <formula>CASE(
  Gender__c , 
  &quot;Male&quot;, &quot;男性&quot;, 
  &quot;Female&quot;, &quot;女性&quot;, 
  &quot;&quot; 
)</formula>
        <label>FML Gender</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Job_Title__c</fullName>
        <label>Job Title</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name_Kana__c</fullName>
        <label>Last Name Kana</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Rank_Ref__c</fullName>
        <formula>CASE(Rank__c , 
&quot;S&quot;, &quot;0157F000000lbTk&quot;, 
&quot;A&quot;, &quot;0157F000000lbTu&quot;, 
&quot;B&quot;, &quot;0157F000000lbTz&quot;, 
&quot;C&quot;, &quot;0157F000000lbU4&quot;, 
&quot;D&quot;, &quot;0157F000000lbUE&quot;, 
&quot;E&quot;, &quot;0157F000000lbUJ&quot;, 
&quot;F&quot;, &quot;0157F000000lbUO&quot;,
&quot;&quot;
)</formula>
        <label>FML Rank Ref</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <label>Rank</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>S</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>F</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rating_Disp__c</fullName>
        <formula>IMAGE( 
  CASE(Rating__c, 
    5, &quot;/img/samples/stars_500.gif&quot;, 
    4, &quot;/img/samples/stars_400.gif&quot;, 
    3, &quot;/img/samples/stars_300.gif&quot;, 
    2, &quot;/img/samples/stars_200.gif&quot;,
    1, &quot;/img/samples/stars_100.gif&quot;,
    &quot;/img/samples/stars_000.gif&quot;
  ), &quot;Unknown&quot;
)</formula>
        <label>FML Rating</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recent_Achievement__c</fullName>
        <label>Recent Achievement</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Thumbnail__c</fullName>
        <label>Thumbnail</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Employee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Display Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mytalent/main/default/src/objects/Employee_Hiring__c.object
<CustomObject>
    <fields>
        <fullName>Current_Address__c</fullName>
        <label>Current Address</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Emergency_Contact__c</fullName>
        <label>Emergency Contact</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hire_Date_Disp__c</fullName>
        <formula>IF(
  ISBLANK(Hire_Date__c),
  &quot;&quot;,
  TEXT(YEAR(Hire_Date__c))+ &quot;/&quot; +TEXT(MONTH(Hire_Date__c))+ &quot;/&quot; +TEXT(DAY(Hire_Date__c))
  + &quot;（勤続&quot; + TEXT(FLOOR((TODAY() - Hire_Date__c)/365.2425)) + &quot;年）&quot;
)</formula>
        <label>FML Hire Date</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hire_Date__c</fullName>
        <label>Hire Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Job_Category__c</fullName>
        <label>Job Category</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rank_Ref_CM__c</fullName>
        <formula>CASE(Rank__c , 
&quot;S&quot;, &quot;0687F000000lRD1&quot;, 
&quot;A&quot;, &quot;0687F000000lRCv&quot;, 
&quot;B&quot;, &quot;0687F000000lRCw&quot;, 
&quot;C&quot;, &quot;0687F000000lRCx&quot;, 
&quot;D&quot;, &quot;0687F000000lRCy&quot;, 
&quot;E&quot;, &quot;0687F000000lRCz&quot;, 
&quot;F&quot;, &quot;0687F000000lRD0&quot;, 
&quot;&quot; 
)</formula>
        <label>FML Rank Ref CM</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rank_Ref__c</fullName>
        <formula>CASE(Rank__c , 
&quot;S&quot;, &quot;0157F000000lbTk&quot;, 
&quot;A&quot;, &quot;0157F000000lbTu&quot;, 
&quot;B&quot;, &quot;0157F000000lbTz&quot;, 
&quot;C&quot;, &quot;0157F000000lbU4&quot;, 
&quot;D&quot;, &quot;0157F000000lbUE&quot;, 
&quot;E&quot;, &quot;0157F000000lbUJ&quot;, 
&quot;F&quot;, &quot;0157F000000lbUO&quot;, 
&quot;&quot; 
)</formula>
        <label>FML Rank Ref</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <label>Rank</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>S</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>F</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rating_Disp__c</fullName>
        <formula>IMAGE( 
CASE(Rating__c, 
5, &quot;/img/samples/stars_500.gif&quot;, 
4, &quot;/img/samples/stars_400.gif&quot;, 
3, &quot;/img/samples/stars_300.gif&quot;, 
2, &quot;/img/samples/stars_200.gif&quot;, 
1, &quot;/img/samples/stars_100.gif&quot;, 
&quot;/img/samples/stars_000.gif&quot; 
), &quot;Unknown&quot; 
)</formula>
        <label>FML Rating</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rating_Ref_CM__c</fullName>
        <formula>CASE(Rating__c , 
5, &quot;0687F000000lRDW&quot;, 
4, &quot;0687F000000lRDZ&quot;, 
3, &quot;0687F000000lRDV&quot;, 
2, &quot;0687F000000lRDU&quot;, 
1, &quot;0687F000000lRDP&quot;, 
&quot;&quot; 
)</formula>
        <label>FML Rating Ref CM</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recent_Achievement__c</fullName>
        <label>Recent Achievement</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tel__c</fullName>
        <label>Tel</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Location__c</fullName>
        <label>Work Location</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ffs__c</fullName>
        <label>ffs</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Employee Hiring</label>
    <nameField>
        <displayFormat>PVT-{0000}</displayFormat>
        <label>Employee Code</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EmployeeController.cls
global with sharing class EmployeeController {
	
    /* Get all data or filter display with pagging */
    @AuraEnabled
    public static EmployeePagedResult findAll(String searchKey, Decimal minPrice, Decimal maxPrice, Decimal pageSize, Decimal pageNumber) {
		Integer pSize = (Integer)pageSize;
        String key = '%' + searchKey + '%';
        Integer offset = ((Integer)pageNumber - 1) * pSize;
        EmployeePagedResult r =  new EmployeePagedResult();
        r.pageSize = pSize;
        r.page = (Integer) pageNumber;
        r.total = [SELECT count() FROM Employee__c
                      WHERE (Name LIKE :key OR rank__c LIKE :key)
                      ];
        r.employees = [SELECT Id, Name, user__c, User__r.Username,
                       		job__c, job_title__c, rank__c, recent_achievement__c,
                            thumbnail__c, Rank_Ref__c
                      FROM Employee__c
                      WHERE (Name LIKE :key OR rank__c LIKE :key)
                      ORDER BY user__c LIMIT :pSize OFFSET :offset];
        System.debug(r);
        return r;
    }

	/* Get info by Id  */
    @AuraEnabled
    public static Object findById(Id employeeId) {
        return [
            SELECT Id, User__c, Employee_Hiring__c, Picture__c, 
            		Employee_Hiring__r.Rank__c, Employee_Hiring__r.Rating__c, 
            		Employee_Hiring__r.Job_Category__c, Employee_Hiring__r.Position__c, Employee_Hiring__r.Status__c, 
            		Employee_Hiring__r.Department__c, Employee_Hiring__r.Work_Location__c, 
            		Employee_Hiring__r.Current_Address__c, Employee_Hiring__r.ffs__c, 
            		Employee_Hiring__r.Tel__c, Employee_Hiring__r.Emergency_Contact__c, 
					Employee_Hiring__r.Email__c, Employee_Hiring__r.Hire_Date__c, 
					Employee_Hiring__r.Recent_Achievement__c, 
            		Employee_Hiring__r.Rating_Disp__c, 
            		Employee_Hiring__r.Rank_Ref_CM__c, Employee_Hiring__r.Rating_Ref_CM__c, 
            		Name, First_Name__c, Last_Name__c, First_Name_Kana__c, Last_Name_Kana__c,
            		Employee_Hiring__r.Hire_Date_Disp__c, Birthday_Disp__c, 
            		Brithday__c, Gender__c, Gender_Disp__c
            FROM Employee__c
            WHERE Id=:employeeId
        ];
    }
}