mytalent/main/default/src/objects/Employee__c.object
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Display Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

talent-app/main/default/objects/Employee_Project__c/Employee_Project__c.object-meta.xml
<CustomObject>
    <label>Employee Project</label>
    <nameField>
        <label>Code Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Employee_Project__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Project</relationshipLabel>
    <relationshipName>Employee_Project</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Employee_Skill__c/Employee_Skill__c.object-meta.xml
<CustomObject>
    <label>Employee Skill</label>
    <nameField>
        <label>Code Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Employee_Skill__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Skill</relationshipLabel>
    <relationshipName>Employee_Skill</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Employee_Skill__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Employee Skill</relationshipLabel>
    <relationshipName>Employee_Skill</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Employee_Skill__c/fields/Skill_Level__c.field-meta.xml
<CustomField>
    <fullName>Skill_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill Level</label>
    <referenceTo>Skill_Level__c</referenceTo>
    <relationshipLabel>Employee Skill</relationshipLabel>
    <relationshipName>Employee_Skill</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Project_Skill__c/Project_Skill__c.object-meta.xml
<CustomObject>
    <label>Project Skill</label>
    <nameField>
        <label>Code Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

talent-app/main/default/objects/Project_Skill__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Project Skill</relationshipLabel>
    <relationshipName>Project_Skill</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Project_Skill__c/fields/Employee_Project__c.field-meta.xml
<CustomField>
    <fullName>Employee_Project__c</fullName>
    <label>Employee Project</label>
    <referenceTo>Employee_Project__c</referenceTo>
    <relationshipLabel>Project Skill</relationshipLabel>
    <relationshipName>Project_Skill</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

talent-app/main/default/objects/Project_Skill__c/fields/Employee_Skill__c.field-meta.xml
<CustomField>
    <fullName>Employee_Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Skill</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Employee_Skill__c.Employee__c</field>
            <operation>equals</operation>
            <valueField>$Source.Employee__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Employee_Skill__c</referenceTo>
    <relationshipLabel>Project Skill</relationshipLabel>
    <relationshipName>Project_Skill</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Project_Skill__c/fields/Skill_Level__c.field-meta.xml
<CustomField>
    <fullName>Skill_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill Level</label>
    <referenceTo>Skill_Level__c</referenceTo>
    <relationshipLabel>Project Skill</relationshipLabel>
    <relationshipName>Project_Skill</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Skill_Level__c/Skill_Level__c.object-meta.xml
<CustomObject>
    <label>Skill Level</label>
    <nameField>
        <label>Skill Level Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/classes/TMRSSCRUD.cls
public class TMRSSCRUD {
    /***********************************/
    /******         Employee Skill         ******/
    /***********************************/
    /* Insert Employee Skill  */
    public TMMessage toSaveEmpSkill(String employeeId, String skillId, String skillLevelId) {
        return toSaveEmpSkill(null, employeeId, skillId, skillLevelId);
    }
    
    /* Update Employee Skill  */
    public TMMessage toSaveEmpSkill(String currId, String employeeId, String skillId, String skillLevelId) {
        Savepoint savePoint = Database.setSavepoint();
        TMMessage resultSet = new TMMessage();
        TMValidate validate = new TMValidate();
        TMSkillCRUD skillModal = new TMSkillCRUD();
        
        try {
            // Validate parameters
            validate.checkAuthorized(employeeId);
            
            if (currId == null) {	// Add
                Employee_Skill__c empSkill = new Employee_Skill__c();
                empSkill.Employee__c = employeeId;
                empSkill.Skill__c = skillId;
                empSkill.Skill_Level__c = skillLevelId;
                insert empSkill;
                // Get back data for display on UI
                resultSet.result = skillModal.getEmpSkill(empSkill.Id);
                
            } else {	// Update
                Employee_Skill__c empSkill = skillModal.getEmpSkill(currId);
                if (employeeId != null) empSkill.Employee__c = employeeId;
                if (skillId != null) empSkill.Skill__c = skillId;
                if (skillLevelId != null) empSkill.Skill_Level__c = skillLevelId;
                update empSkill;
                // Get back data for display on UI
                resultSet.result = skillModal.getEmpSkill(empSkill.Id);
            }
            
        } catch(Exception e) {
            Database.rollback(savePoint);
            resultSet.setErrMessage(e.getMessage());
        }
        
        return resultSet;
    }
    
    
    /***********************************/
    /******           Project Skill           ******/
    /***********************************/
    /* Insert Project Skill  */
    public TMMessage toSaveProjectSkill(String employeeId, String projectId, String empSkillId, String skillLevelId) {
        return toSaveProjectSkill(null, employeeId, projectId, empSkillId, skillLevelId);
    }
    
    /* Update Project Skill  */
    public TMMessage toSaveProjectSkill(String currId, String employeeId, String projectId, String empSkillId, String skillLevelId) {
        Savepoint savePoint = Database.setSavepoint();
        TMMessage resultSet = new TMMessage();
        TMValidate validate = new TMValidate();
        TMSkillCRUD skillModal = new TMSkillCRUD();
        
        try {
            // Validate parameters
            validate.checkAuthorized(employeeId);
            
            if (currId == null) {	// Add
                Project_Skill__c pjSkill = new Project_Skill__c();
                pjSkill.Employee__c = employeeId;
                pjSkill.Employee_Project__c = projectId;
                pjSkill.Employee_Skill__c = empSkillId;
                pjSkill.Skill_Level__c = skillLevelId;
                insert pjSkill;
                // Get back data for display on UI
                resultSet.result = skillModal.getProjectSkill(pjSkill.Id);
                
            } else {	// Update
                Project_Skill__c pjSkill = skillModal.getProjectSkill(currId);
                if (employeeId != null) pjSkill.Employee__c = employeeId;
                if (projectId != null) pjSkill.Employee_Project__c = projectId;
                if (empSkillId != null) pjSkill.Employee_Skill__c = empSkillId;
                if (skillLevelId != null) pjSkill.Skill_Level__c = skillLevelId;
                update pjSkill;
                // Get back data for display on UI
                resultSet.result = skillModal.getProjectSkill(pjSkill.Id);
            }
            
        } catch(Exception e) {
            Database.rollback(savePoint);
            resultSet.setErrMessage(e.getMessage());
        }
        
        return resultSet;
    }
}