mytalent/main/default/src/objects/Employee__c.object
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Display Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

talent-app/main/default/objects/Employee_Project__c/Employee_Project__c.object-meta.xml
<CustomObject>
    <label>Employee Project</label>
    <nameField>
        <label>Code Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Employee_Project__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Project</relationshipLabel>
    <relationshipName>Employee_Project</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Employee_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Employee Project</relationshipLabel>
    <relationshipName>Employee_Project</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Employee_Skill__c/Employee_Skill__c.object-meta.xml
<CustomObject>
    <label>Employee Skill</label>
    <nameField>
        <label>Code Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Employee_Skill__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Skill</relationshipLabel>
    <relationshipName>Employee_Skill</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Employee_Skill__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Employee Skill</relationshipLabel>
    <relationshipName>Employee_Skill</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Employee_Skill__c/fields/Skill_Level__c.field-meta.xml
<CustomField>
    <fullName>Skill_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill Level</label>
    <referenceTo>Skill_Level__c</referenceTo>
    <relationshipLabel>Employee Skill</relationshipLabel>
    <relationshipName>Employee_Skill</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Project_Skill__c/Project_Skill__c.object-meta.xml
<CustomObject>
    <label>Project Skill</label>
    <nameField>
        <label>Code Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

talent-app/main/default/objects/Project_Skill__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Project Skill</relationshipLabel>
    <relationshipName>Project_Skill</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Project_Skill__c/fields/Employee_Project__c.field-meta.xml
<CustomField>
    <fullName>Employee_Project__c</fullName>
    <label>Employee Project</label>
    <referenceTo>Employee_Project__c</referenceTo>
    <relationshipLabel>Project Skill</relationshipLabel>
    <relationshipName>Project_Skill</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

talent-app/main/default/objects/Project_Skill__c/fields/Employee_Skill__c.field-meta.xml
<CustomField>
    <fullName>Employee_Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Skill</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Employee_Skill__c.Employee__c</field>
            <operation>equals</operation>
            <valueField>$Source.Employee__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Employee_Skill__c</referenceTo>
    <relationshipLabel>Project Skill</relationshipLabel>
    <relationshipName>Project_Skill</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Project_Skill__c/fields/Skill_Level__c.field-meta.xml
<CustomField>
    <fullName>Skill_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill Level</label>
    <referenceTo>Skill_Level__c</referenceTo>
    <relationshipLabel>Project Skill</relationshipLabel>
    <relationshipName>Project_Skill</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Skill__c/fields/Skill_Type__c.field-meta.xml
<CustomField>
    <fullName>Skill_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill Type</label>
    <referenceTo>Skill_Type__c</referenceTo>
    <relationshipLabel>Skill</relationshipLabel>
    <relationshipName>Skill</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Skill_Level__c/Skill_Level__c.object-meta.xml
<CustomObject>
    <label>Skill Level</label>
    <nameField>
        <label>Skill Level Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Skill_Level__c/fields/Skill_Num__c.field-meta.xml
<CustomField>
    <fullName>Skill_Num__c</fullName>
    <label>Skill Num</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

talent-app/main/default/objects/Skill_Type__c/Skill_Type__c.object-meta.xml
<CustomObject>
    <label>Skill Type</label>
    <nameField>
        <label>Type Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/classes/TMRSS.cls
public class TMRSS {
    /* Get RSS Skill info by Id  */
    @AuraEnabled
    public static Object getRSSSkill(Id employeeId) {
        return [
            SELECT Employee__r.Name, Id, Name, 
                	Skill__r.Name, Skill__r.Skill_Type__r.Name, 
            		Skill__r.Skill_Type__r.Order__c, 
                	Skill_Level__r.Name, Skill_Level__r.Skill_Num__c
            FROM Employee_Skill__c
            WHERE Employee__c = :employeeId
            ORDER BY Skill__r.Skill_Type__r.Order__c
        ];
    }
    
    /* Get RSS Project info by Id  */
    @AuraEnabled
    public static Object getRSSProject(Id employeeId) {
        return [
            SELECT Employee__r.Name, Id, Name, Project__r.Name, 
                    (
                        SELECT Employee_Skill__r.Skill__r.Name, 
                                Employee_Skill__r.Skill__r.Skill_Type__r.Name, 
                        		Employee_Skill__r.Skill__r.Skill_Type__r.Order__c, 
                                Employee_Skill__r.Skill_Level__r.Name, 
                                Employee_Skill__r.Skill_Level__r.Skill_Num__c
                        FROM Project_Skill__r
                        ORDER BY Employee_Skill__r.Skill__r.Skill_Type__r.Order__c
                    )
            FROM Employee_Project__c
            WHERE Employee__c = :employeeId
        ];
    }
    
    //--------------------------------------------------------------------//
    /* Get list all Skill types  */
    @AuraEnabled
    public static List<Skill_Type__c> fetchSkillType() {
        return TMSkill.fetchSkill();
    }
    
    /* Count number of indivisual Skills */
    @AuraEnabled
    public static integer countSkill(Id employeeId) {
        String query = 'SELECT COUNT() ' +
            'FROM Employee_Skill__c ' +
            'WHERE Employee__c = :employeeId';
        integer count= Database.countQuery(query);
        return count;
    }
    
    /* Get list Projects  */
    @AuraEnabled
    public static List<Object> fetchProject(Id employeeId) {
        return [
            SELECT Employee__r.Name, Id, Name, Project__r.Name
            FROM Employee_Project__c
            WHERE Employee__c = :employeeId
        ];
    }
    
    /* Get indivisual Skill info  */
    @AuraEnabled
    public static List<Object> fetchSkill(Id employeeId, Id typeId) {
        String query = '';
        query += 'SELECT Employee__r.Name, Id, Name, ' +
            	'Skill__r.Name, Skill__r.Skill_Type__r.Name, ' +
            	'Skill__r.Skill_Type__r.Order__c, ' +
            	'Skill_Level__r.Name, Skill_Level__r.Skill_Num__c ' +
            'FROM Employee_Skill__c ' +
            'WHERE Employee__c = :employeeId ' +
            	'AND Skill__r.Skill_Type__c = :typeId';
        
        List<Object> result = new List<Object>();
        result.Add(Database.query(query).Size());
        result.Add(Database.query(query));
        return result;
    }
    
    /* Get Skill info depend on each Project */
    @AuraEnabled
    public static List<Object> fetchProjectSkill(Id employeeId, Id projectId, Id typeId) {
        String query = '';
        query += 'SELECT Id, Skill_Level__r.Skill_Num__c, ' +
            	'Employee_Project__r.Project__r.Name, ' +
            	'Employee_Skill__r.Skill__r.Name, ' +
            	'Employee_Skill__r.Skill__r.Skill_Type__r.Name, ' +
            	'Employee_Skill__r.Skill__r.Skill_Type__r.Order__c, ' +           
            	'Employee_Skill__r.Skill_Level__r.Name, ' +
            	'Employee_Skill__r.Skill_Level__r.Skill_Num__c ' +
            'FROM Project_Skill__c ' +
            'WHERE Employee_Project__c = :projectId ' +
            	'AND Employee_Skill__r.Skill__r.Skill_Type__c = :typeId';
        
        List<Object> result = new List<Object>();
        result.Add(Database.query(query).Size());
        result.Add(Database.query(query));
        return result;
    }
}