mytalent/main/default/src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Employee_Hiring__c</fullName>
        <label>Employee Hiring</label>
        <referenceTo>Employee_Hiring__c</referenceTo>
        <relationshipLabel>Employee</relationshipLabel>
        <relationshipName>Employee</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Display Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mytalent/main/default/src/objects/Employee_Hiring__c.object
<CustomObject>
    <fields>
        <fullName>Job_Category__c</fullName>
        <label>Job Category</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Location__c</fullName>
        <label>Work Location</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>Employee Hiring</label>
    <nameField>
        <displayFormat>PVT-{0000}</displayFormat>
        <label>Employee Code</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Employee_Hiring__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

mytalent/main/default/src/objects/EvaluationComment__c.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>EvaluationComment</label>
    <nameField>
        <label>E Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/EvaluationComment__c/fields/Create_By__c.field-meta.xml
<CustomField>
    <fullName>Create_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Create By</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Evaluation Comment (Create By)</relationshipLabel>
    <relationshipName>Evaluation_Comment1</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/EvaluationComment__c/fields/Create_When_Disp__c.field-meta.xml
<CustomField>
    <fullName>Create_When_Disp__c</fullName>
    <formula>IF( 
ISBLANK(Create_When__c), 
"", 
TEXT(YEAR(DATEVALUE(Create_When__c))) + "/" + TEXT(MONTH(DATEVALUE(Create_When__c))) + "/" +TEXT(DAY(DATEVALUE(Create_When__c))) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FML Create When</label>
    <type>Text</type>
</CustomField>

talent-app/main/default/objects/EvaluationComment__c/fields/Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>Employee_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee ID</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Evaluation Comment</relationshipLabel>
    <relationshipName>Evaluation_Comment</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/EvaluationComment__c/fields/Last_Modified_When__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_When__c</fullName>
    <label>Last Modified When</label>
    <type>DateTime</type>
</CustomField>

talent-app/main/default/objects/Personality_Comment__c/Personality_Comment__c.object-meta.xml
<CustomObject>
    <label>Personality Comment</label>
    <nameField>
        <label>Content</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Personality_Comment__c/fields/Create_By__c.field-meta.xml
<CustomField>
    <fullName>Create_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Create By</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Personality Comment (Create By)</relationshipLabel>
    <relationshipName>Personality_Comment1</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Personality_Comment__c/fields/Create_When__c.field-meta.xml
<CustomField>
    <fullName>Create_When__c</fullName>
    <label>Create When</label>
    <type>DateTime</type>
</CustomField>

talent-app/main/default/objects/Personality_Comment__c/fields/Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>Employee_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee ID</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Personality Comment</relationshipLabel>
    <relationshipName>Personality_Comment</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Skill_Comment__c/Skill_Comment__c.object-meta.xml
<CustomObject>
    <label>Skill Comment</label>
    <nameField>
        <label>Content</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Skill_Comment__c/fields/Create_By__c.field-meta.xml
<CustomField>
    <fullName>Create_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Create By</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Skill Comment (Create By)</relationshipLabel>
    <relationshipName>Skill_Comment1</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Skill_Comment__c/fields/Create_When_Disp__c.field-meta.xml
<CustomField>
    <fullName>Create_When_Disp__c</fullName>
    <formula>IF(
ISBLANK(Create_When__c),
"",
TEXT(YEAR(DATEVALUE(Create_When__c))) + "/" + TEXT(MONTH(DATEVALUE(Create_When__c))) + "/" +TEXT(DAY(DATEVALUE(Create_When__c)))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FML Create When</label>
    <type>Text</type>
</CustomField>

talent-app/main/default/objects/Skill_Comment__c/fields/Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>Employee_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee ID</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Skill Comment</relationshipLabel>
    <relationshipName>Skill_Comment</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Skill_Comment__c/fields/Skill_Level_ID__c.field-meta.xml
<CustomField>
    <fullName>Skill_Level_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Skill Level ID</label>
    <referenceTo>Skill_Level__c</referenceTo>
    <relationshipLabel>Skill Comment</relationshipLabel>
    <relationshipName>Skill_Comment</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Skill_Level__c/Skill_Level__c.object-meta.xml
<CustomObject>
    <label>Skill Level</label>
    <nameField>
        <label>Skill Level Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Skill_Level__c/fields/Skill_Num__c.field-meta.xml
<CustomField>
    <fullName>Skill_Num__c</fullName>
    <label>Skill Num</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

talent-app/main/default/classes/TMEvaluationComment.cls
public class TMEvaluationComment {
    public static Employee__c currentUser;
    
    public TMEvaluationComment() {
        currentUser = TMHome.getUserInfo();
    }
    
    private static Integer calculateSkillComment(Id employeeId, Id modeId, String dateFrom, String dateTo) {
        System.debug(dateFrom);
        Date dtFrom = dateFrom == null ? null : Date.parse (dateFrom);
        Date dtTo = dateTo == null ? null : Date.parse (dateTo);
        
        String query = '';
        query += 'SELECT ID ' +
            'FROM Skill_Comment__c ' +
            'WHERE Employee_ID__c = :employeeID ' +
            'AND Skill_Level_ID__c = :modeId ';
        if (dtFrom != null && dtTo != null)
        {
            query += 'AND Create_When__c >= :dtFrom AND Create_When__c <= :dtTo ';
        }
        else if (dtFrom != null) {
            query += 'AND Create_When__c >= :dtFrom ';
        }
        else if (dtTo != null) {
            query += 'AND Create_When__c <= :dtTo ';
        }
        
       	return Database.query(query).Size();
    }
    
    private static Integer calculatePersonalityComment(Id employeeId, String dateFrom, String dateTo) {
        System.debug(dateFrom);
        Date dtFrom = dateFrom == null ? null : Date.parse (dateFrom);
        Date dtTo = dateTo == null ? null : Date.parse (dateTo);
        
        String query = '';
        query += 'SELECT ID ' +
            'FROM Personality_Comment__c ' +
            'WHERE Employee_ID__c = :employeeID ';
        if (dtFrom != null && dtTo != null)
        {
            query += 'AND Create_When__c >= :dtFrom AND Create_When__c <= :dtTo ';
        }
        else if (dtFrom != null) {
            query += 'AND Create_When__c >= :dtFrom ';
        }
        else if (dtTo != null) {
            query += 'AND Create_When__c <= :dtTo ';
        }
        
       	return Database.query(query).Size();
    }
    
    @AuraEnabled
   	public static TMEvaluation evaluateComment(Id employeeId, String dateFrom, String dateTo) {
        Id motivatedLevel = [SELECT Id FROM Skill_Level__c WHERE Skill_Num__c = 1 LIMIT 1].Id;
        Id goodLevel = [SELECT Id FROM Skill_Level__c WHERE Skill_Num__c = 3 LIMIT 1].Id;
        Id excellentLevel = [SELECT Id FROM Skill_Level__c WHERE Skill_Num__c = 4 LIMIT 1].Id;
            
        TMEvaluation result = new TMEvaluation();
        result.achievement = calculateSkillComment(employeeId, excellentLevel, dateFrom, dateTo) * 2 + calculateSkillComment(employeeId, goodLevel, dateFrom, dateTo);
        result.obliging = calculatePersonalityComment(employeeId, dateFrom, dateTo);
        result.achievementOfTask = calculateSkillComment(employeeId, motivatedLevel, dateFrom, dateTo) + calculateSkillComment(employeeId, excellentLevel, dateFrom, dateTo);

        return result;
    }
    
	@AuraEnabled
   	public static List<EvaluationComment__c> fetchEvaluationComment(Id employeeId, String dateFrom, String dateTo) {
        Date dtFrom = dateFrom == null ? null : Date.parse (dateFrom);
        Date dtTo = dateTo == null ? null : Date.parse (dateTo);
      	List <EvaluationComment__c> lstComment = new List<EvaluationComment__c>();
        
        String query = '';
        query += 'SELECT ID, ' +
            			'Create_When_Disp__c, ' +
                        'Create_By__r.Name, ' +
                        'Create_By__r.Employee_Hiring__r.Job_Category__c, ' +
                        'Create_By__r.Employee_Hiring__r.Position__c, ' +
                        'Create_By__r.Employee_Hiring__r.Team__c, ' +
            			'Create_By__r.Employee_Hiring__r.Work_Location__c, ' +
                        'LastModifiedById, ' +
                        'Last_Modified_When__c, ' +
                        'Name ' +
            	'FROM EvaluationComment__c ' +
            	'WHERE Employee_ID__c = :employeeID ';
        if (dtFrom != null && dtTo != null)
        {
            query += 'AND Create_When__c >= :dtFrom AND Create_When__c <= :dtTo ';
        }
        else if (dtFrom != null) {
            query += 'AND Create_When__c >= :dtFrom ';
        }
        else if (dtTo != null) {
            query += 'AND Create_When__c <= :dtTo ';
        }
        query += 'ORDER BY Create_When__c DESC';
        
       	lstComment = Database.query(query);
        return lstComment;
	}
    
    @AuraEnabled
	public static List<Object> addEvaluationComment (String createById, String employeeId, String comment) {
        List<Object> result = new List<Object>();
        Savepoint savePoint = Database.setSavepoint();
        TMResponseMessage message = new TMResponseMessage();
        
        if (!TMHome.isManager()) {
            message.status = 'error';
            message.message = '権限がない。';
            result.Add(message);
            return result;
        }
        
        try
        {
            DateTime current = system.now();
            EvaluationComment__c item = new EvaluationComment__c();
            item.Create_By__c = createById;
            item.Create_When__c = current;
            item.Employee_ID__c = employeeId;
            item.Last_Modified_When__c = current;
            item.Name = comment;
            insert item;
            
            message.status = 'OK';
            result.Add(message);
            result.Add(getEvaluationComment(item.Id));
        }
        catch(Exception e)
        {
        	Database.rollback(savePoint);
            message.status = 'error';
            message.message = e.getMessage();
            result.Add(message);
        }
        
        return result;
    }
    
    @AuraEnabled
	public static List<Object> editEvaluationComment (Id itemId, String comment) {
        List<Object> result = new List<Object>();
        Savepoint savePoint = Database.setSavepoint();
        TMResponseMessage message = new TMResponseMessage();
        
        if (!TMHome.isManager()) {
            message.status = 'error';
            message.message = '権限がない。';
            result.Add(message);
            return result;
        }
        
        List<EvaluationComment__c> item = getEvaluationComment(itemId);
        if (item.isEmpty()) {
            message.status = 'error';
            message.message = 'データが存在していません。';
            result.Add(message);
            return result;
        }
        if(TMHome.getCurrentUser().Id != item[0].Create_By__c) {
            message.status = 'error';
            message.message = 'このデータに権限がない。';
            result.Add(message);
            return result;
        }
        
        try
        {
            DateTime current = system.now();
            item[0].Name = comment;
            item[0].Last_Modified_When__c = current;
            update item;
            
            message.status = 'OK';
            result.Add(message);
            result.Add(getEvaluationComment(item[0].Id));
        }
        catch(Exception e)
        {
        	Database.rollback(savePoint);
            message.status = 'error';
            message.message = e.getMessage();
            result.Add(message);
        }
        
        return result;
    }
    
    @AuraEnabled
    public static List<Object> deleteEvaluationComment(Id itemId) {
        List<Object> result = new List<Object>();
        Savepoint savePoint = Database.setSavepoint();
        TMResponseMessage message = new TMResponseMessage();
        
        if (!TMHome.isManager()) {
            message.status = 'error';
            message.message = '権限がない。';
            result.Add(message);
            return result;
        }
        
        List<EvaluationComment__c> item = getEvaluationComment(itemId);
        if (item.isEmpty()) {
            message.status = 'error';
            message.message = 'データが存在していません。';
            result.Add(message);
            return result;
        }
        if(TMHome.getCurrentUser().Id != item[0].Create_By__c) {
            message.status = 'error';
            message.message = 'このデータに権限がない。';
            result.Add(message);
            return result;
        }
        
        try
        {
            delete item;
            
            message.status = 'OK';
            result.Add(message);
        }
        catch(Exception e)
        {
        	Database.rollback(savePoint);
            message.status = 'error';
            message.message = e.getMessage();
            result.Add(message);
        }
        
        return result;
	}
    
    @AuraEnabled
    public static List<EvaluationComment__c> getEvaluationComment(Id itemId) {
        return [SELECT ID, 
                Create_When_Disp__c,
                Create_By__r.Name,
                Create_By__r.Employee_Hiring__r.Job_Category__c,
                Create_By__r.Employee_Hiring__r.Position__c,
                Create_By__r.Employee_Hiring__r.Team__c,
                Create_By__r.Employee_Hiring__r.Work_Location__c,
                LastModifiedById, 
                Last_Modified_When__c,
                Name
            FROM EvaluationComment__c
            WHERE Id = :itemId
 		];
	}
}