mytalent/main/default/src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Employee_Hiring__c</fullName>
        <label>Employee Hiring</label>
        <referenceTo>Employee_Hiring__c</referenceTo>
        <relationshipLabel>Employee</relationshipLabel>
        <relationshipName>Employee</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Thumbnail__c</fullName>
        <label>Thumbnail</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Employee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Display Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mytalent/main/default/src/objects/Employee_Hiring__c.object
<CustomObject>
    <label>Employee Hiring</label>
    <nameField>
        <displayFormat>PVT-{0000}</displayFormat>
        <label>Employee Code</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/objects/Employee_Hiring__c/fields/Permission__c.field-meta.xml
<CustomField>
    <fullName>Permission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Permission</label>
    <referenceTo>Permission__c</referenceTo>
    <relationshipLabel>Employee Hiring</relationshipLabel>
    <relationshipName>Employee_Hiring</relationshipName>
    <type>Lookup</type>
</CustomField>

talent-app/main/default/objects/Permission__c/Permission__c.object-meta.xml
<CustomObject>
    <label>Permission</label>
    <nameField>
        <label>Permission Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/classes/TMHome.cls
public class TMHome {
	@AuraEnabled
    public static Employee__c getUserInfo() {
        return [
            SELECT ID, 
            	Name, 
            	Thumbnail__c,
            	User__c,
            	Employee_Hiring__r.Permission__r.Name 
            FROM Employee__c 
            WHERE User__c = :UserInfo.getUserId() 
            LIMIT 1
        ];
    }
    
    @AuraEnabled
    public static String[] customLogout() {
        return new String[] {
            'https://pnx-tm-dev-ed.my.salesforce.com',
            Site.getBaseInsecureUrl()
        };
    }
}