mytalent/main/default/src/objects/EvaluationComment__c.object
<CustomObject>
    <fields>
        <fullName>Author__c</fullName>
        <label>Author</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DateComment__c</fullName>
        <label>DateComment</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubDepartment__c</fullName>
        <label>SubDepartment</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>EvaluationComment</label>
    <nameField>
        <label>E Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

talent-app/main/default/classes/TMSearchComment.cls
public class TMSearchComment {
	@AuraEnabled
   	public static List<EvaluationComment__c> searchComment(String DateFrom, String DateTo) {
        Date dt_from = DateFrom == null ? null : Date.parse (DateFrom);
        Date dt_to = DateTo == null ? null : Date.parse (DateTo);
      	List <EvaluationComment__c> lst = new List<EvaluationComment__c>();
        
        String query = '';
        query += 'SELECT DateComment__c, Department__c, SubDepartment__c, Team__c, Branch__c, Comment__c, Author__c FROM EvaluationComment__c ';
        if (dt_from != null && dt_to != null)
        {
            query += ' WHERE DateComment__c >= :dt_from AND DateComment__c <= :dt_to';
        }
        else if (dt_from != null) {
            query += ' WHERE DateComment__c >= :dt_from';
        }
        else if (dt_to != null) {
            query += ' WHERE DateComment__c <= :dt_to';
        }
        
       	lst = Database.query(query);
        return lst;
	}
}